client_config_backend: settings
client_config:
  client_id: 736016274811-tl3tli7laq79u7mkh35f0a5ujc68m49e.apps.googleusercontent.com
  client_secret: QzUhieOpKs5RGo2RxMo8oCwa

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install